.PHONY: default
default: drift
logs:
	./main -project myfreegke -state gs://test-stateconcile/terraform.tfstate -logs
drift:
	./main -project myfreegke -state gs://test-stateconcile/terraform.tfstate
